### PR TITLE
Update Advanced Achievements hook

### PR DESCRIPTION
**Pull request by PyvesB**
Hello there!

This pull request updates the Advanced Achievements hook to use the new standalone API artifact. Note that doing so will only work with plugin versions 5.8.0 onwards, so you'll have to warn users in the update changelog. I could implement a workaround for the hook to work with 5.7.0+, but that will add quite a bit of code inside _AdvancedAchievementsHook_ (~15 lines). Let me know what you think!

Submitting the pull request to _master_ as there is no version specific branch yet. 😉 

Cheers,

Pyves

### CODE REVIEW

File: PlanPluginBridge/src/main/java/com/djrapitops/pluginbridge/plan/advancedachievements/AdvancedAchievementsHook.java [hunk 1]
```diff
@@ -29,12 +28,12 @@ public AdvancedAchievementsHook(HookHandler hookH) {
         super("com.hm.achievement.AdvancedAchievements", hookH);
     }
 
-    public void hook() throws NoClassDefFoundError {
+    @Override
+	public void hook() throws NoClassDefFoundError {
```
Comment (Rsl1122) [inline PlanPluginBridge/src/main/java/com/djrapitops/pluginbridge/plan/advancedachievements/AdvancedAchievementsHook.java]: This line seems to have a tab instead of spaces like rest of the code

**Comment by PyvesB** [comment]
Fixed the tab! By the way Travis seems to be struggling with SonarQube.

I think @Platinteufel's idea would be the easiest to implement. I would imagine it as some sort of command retrieving all the database records matching a given achievement and listing players with reception dates in the chat in chronological order. We could use the pagination class (yeah! \o/) and cache the results coming back from the database with a 60 second expiration delay or so (a bit like in _AbstractRankingCommand_). Those are my quick thoughts, but there may be a better way of doing things. ^^

**Comment by Rsl1122** [comment]
Yeah noticed that thing about Travis, but running the build multiple times didn't seem to solve it.

I was trying to get ideas on what to display on Plan, but I guess that didn't come across :)

**Comment by PyvesB** [comment]
Oh, okay, I was thinking in the context of that issue.

An idea that comes to mind would be a pie chart or a bar chart representing the relative amount of players who have received each individual achievement. When you click on one of the slices in the pie or one of the bars, it would list the names of the players who have received that achievement (possibly with the reception date as well).

**Comment by Rsl1122** [comment]
I'll see what I can do :P 

The current API doesn't seem to support getting how many players have received an achievement. I think a Map<String, Set<UUID>> might do the trick, or the other way around - It can be reversed pretty easily after all.

I've found the Travis issue which is caused by encrypted environment variables not being available on Pull Requests. Will be fixed for future PRs :)

Merging this since it's all good. Thanks!
